### ISSUE TITLE
Debug occurs when execution

### ISSUE THREAD

**Issue by legeng** [SixQuant/nowatermark#1]
OpenCV Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /tmp/opencv-20171226-51925-1cq7659/opencv-3.4.0/modules/imgproc/src/color.cpp, line 11111
Traceback (most recent call last):
  File "/data/wwwroot/python/test4.py", line 13, in <module>
    remover.remove_watermark(path + 'anjuke3.jpg', path + 'anjuke3-result.jpg')
  File "/usr/local/lib/python3.6/site-packages/nowatermark/WatermarkRemover.py", line 151, in remove_watermark
    self.watermark_template_mask_img
  File "/usr/local/lib/python3.6/site-packages/nowatermark/WatermarkRemover.py", line 122, in remove_watermark_raw
    img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
cv2.error: /tmp/opencv-20171226-51925-1cq7659/opencv-3.4.0/modules/imgproc/src/color.cpp:11111: error: (-215) scn == 3 || scn == 4 in function cvtColor

**Comment by SixQuant** [comment]
it says your input image should have 3 or 4 channels before applying the function cv2.cvtColor.

so check your image shape before applying the function to print im.shape. if the result is None type (most of the times, this is the problem), your image is not loaded correctly, most probably because your path is not correct.

point is that your image should have 3 dimensions, rows, columns and depth.
